# Generated by Django 5.1.4 on 2024-12-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_completed_task_is_completed_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='now'),
        ),
    ]
